# Page settings

baseURL = "https://kanebetter.github.io/resume"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "G-MRV0T2HZ0C"






[params]
    author = "CowboySmall"
    description = "CV"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "KAIQIN CHEN"
        tagline = "Software Engineer"
        avatar = "avatar.jpg"







    [params.contact]
        enable = true
        location = "Irvine, CA"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "949 742 4400"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:kaiqinc@uci.edu"
        text = "kaiqinc@uci.edu"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://kanebetter.github.io/"
        text = "kanebetter.github.io"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/Angular/React/Vue"
        [[params.skills.list.items]]
        details = "Python/Ruby/PHP"
        [[params.skills.list.items]]
        details = "Node.js/ASP.NET"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Master of Software Engineering"
        university = "University of California, Irvine"
        dates = "2021 - 2022"
        [[params.education.list]]
        degree = "MSc in Agricultural Engineering and Information Technology"
        university = "Zhejiang University"
        dates = "2018 - 2021"
        [[params.education.list]]
        degree = "BSc in Agricultural Resources and Environment"
        university = "Zhejiang University"
        dates = "2014 - 2018"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "Chinese"
        level = "Native"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Skateboarding"
        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "Hi everyone - I am looking for a new role and would appreciate your support. Thank you in advance for any connections, advice, or opportunities you can offer. I will complete my Master’s in Software Engineering in December 2022 from UC Irvine, and now I am actively looking for Full-time position."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Software Engineering Intern"
        dates = "2022.6 - 2022.9"
        company = "Arista Networks, CA"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."









    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/kanebetter"
        title = "kanebetter"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/kaiqinchen"
        title = "kaiqinchen"
        [[params.social.list]]
        icon = "fab fa-youtube-square"
        url = "//youtube.com/channel/UCdo8CzknFdiWYvk9423f-OQ"
        title = "@Kaiqin Chen"




